[package]
name = "rust-elm-gui"
version = "0.1.0"
authors = ["vegapit"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
itertools = "0.8"
statrs = "0.11"